// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD34Ynvu7nEMivvsKKy-p3ArIsQvtqoTcc',
    appId: '1:199131708682:web:6c6d3ad57d0de8e744cef3',
    messagingSenderId: '199131708682',
    projectId: 'machinfy-agent',
    authDomain: 'machinfy-agent.firebaseapp.com',
    storageBucket: 'machinfy-agent.firebasestorage.app',
    measurementId: 'G-DJTGLBK3ZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm62Fa7VjQe4BVhubCVHDDtvrw3yQfQjU',
    appId: '1:199131708682:android:b0426c0215f6b64f44cef3',
    messagingSenderId: '199131708682',
    projectId: 'machinfy-agent',
    storageBucket: 'machinfy-agent.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-9yQe1ejGsJaVB4UMQXzhD4ag6a1bP5M',
    appId: '1:199131708682:ios:c3b345fdbf9cf4ae44cef3',
    messagingSenderId: '199131708682',
    projectId: 'machinfy-agent',
    storageBucket: 'machinfy-agent.firebasestorage.app',
    iosBundleId: 'com.example.machinfyAgent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-9yQe1ejGsJaVB4UMQXzhD4ag6a1bP5M',
    appId: '1:199131708682:ios:c3b345fdbf9cf4ae44cef3',
    messagingSenderId: '199131708682',
    projectId: 'machinfy-agent',
    storageBucket: 'machinfy-agent.firebasestorage.app',
    iosBundleId: 'com.example.machinfyAgent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD34Ynvu7nEMivvsKKy-p3ArIsQvtqoTcc',
    appId: '1:199131708682:web:deb33e6b3a72eed044cef3',
    messagingSenderId: '199131708682',
    projectId: 'machinfy-agent',
    authDomain: 'machinfy-agent.firebaseapp.com',
    storageBucket: 'machinfy-agent.firebasestorage.app',
    measurementId: 'G-8ZNXC1ZN1N',
  );
}
